import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html id="html" lang="en">
      <Head>
        <title>Prime</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/Logo.jpg" />
      </Head>
      <body id="body">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
